export interface OrderStatus {
  ORDER_ENTERING: 1;
  DRAWING: 2;
  MATERIAL_ESTIMATE: 3;
  WAITING_CONFIRMATION: 4;
  MATERIAL_ARRIVAL: 5;
  PRODUCTION: 6;
  DELIVERY: 7;
  INSTALLATION: 8;
  AWAITING_SERVICE: 9;
  SERVICE: 10;
  TO_CLOSE: 11;
  CLOSED: 12;
  CANCELLED: 13;
}
